blocks:
  # Right prompt segments (matching Starship right_format order)
  - type: prompt
    alignment: right
    overflow: hide
    segments:
      # === GIT STATUS/WORKING CHANGES GROUP ===

      # Git branch/HEAD info - standalone when no changes
      - type: git
        style: diamond
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        background: "p:orange"
        foreground: "p:orange_darker"
        template: "{{ if not (or (.Working.Changed) (.Staging.Changed)) }}{{ .UpstreamIcon }} {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }} {{ end }}"
        properties:
          branch_icon: "\ue725 "
          fetch_status: true
          fetch_upstream_icon: true
        background_templates:
          - "{{ if gt .Ahead 0 }}p:green{{ end }}"
          - "{{ if gt .Behind 0 }}p:red{{ end }}"
        foreground_templates:
          - "{{ if gt .Ahead 0 }}p:green_lighter{{ end }}"
          - "{{ if gt .Behind 0 }}p:red_lighter{{ end }}"

      # Git branch/HEAD info - left side of pill when changes exist
      - type: git
        style: diamond
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b0"
        background: "p:orange"
        foreground: "p:orange_darker"
        template: "{{ if or (.Working.Changed) (.Staging.Changed) }}{{ .UpstreamIcon }} {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }} {{ end }}"
        properties:
          branch_icon: "\ue725 "
          fetch_status: true
          fetch_upstream_icon: true
        background_templates:
          - "{{ if gt .Ahead 0 }}p:green{{ end }}"
          - "{{ if gt .Behind 0 }}p:red{{ end }}"
        foreground_templates:
          - "{{ if gt .Ahead 0 }}p:green_lighter{{ end }}"
          - "{{ if gt .Behind 0 }}p:red_lighter{{ end }}"

      # Git working/staging changes - right side of pill
      - type: git
        style: diamond
        trailing_diamond: "\ue0b4 "
        background: "p:yellow"
        foreground: "p:yellow_darker"
        template: "{{ if or (.Working.Changed) (.Staging.Changed) }} {{ if .Working.Changed }}\uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} {{ end }}"
        properties:
          branch_icon: "\ue725 "
          fetch_status: true
          fetch_upstream_icon: true
