blocks:
  - type: prompt
    alignment: right
    overflow: hide
    segments:
      # Node.js runtime version - diamond style when no project segment and has package manager
      - type: node
        style: diamond
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b0"
        background: "p:green"
        foreground: "p:green_lighter"
        template: "{{ if and (not .Segments.Project.Version) (.PackageManagerIcon) }} \ue718  {{ .Major }}.{{ .Minor }} {{ end }}"
        properties:
          fetch_package_manager: true

      # Node.js runtime version - diamond style when no project segment and no package manager
      - type: node
        style: diamond
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        background: "p:green"
        foreground: "p:green_lighter"
        template: "{{ if and (not .Segments.Project.Version) (not .PackageManagerIcon) }} \ue718  {{ .Major }}.{{ .Minor }} {{ end }}"
        properties:
          fetch_package_manager: true

      # Node.js runtime version - powerline style when project segment exists and has package manager
      - type: node
        style: powerline
        powerline_symbol: "\ue0b0"
        background: "p:green"
        foreground: "p:green_lighter"
        template: "{{ if and (.Segments.Project.Version) (.PackageManagerIcon) }} \ue718  {{ .Major }}.{{ .Minor }} {{ end }}"
        properties:
          fetch_package_manager: true

      # Node.js runtime version - diamond end when project segment exists but no package manager
      - type: node
        style: diamond
        trailing_diamond: "\ue0b4 "
        background: "p:green"
        foreground: "p:green_lighter"
        template: "{{ if and (.Segments.Project.Version) (not .PackageManagerIcon) }} \ue718  {{ .Major }}.{{ .Minor }} {{ end }}"
        properties:
          fetch_package_manager: true

      # Package manager info
      - type: node
        style: diamond
        trailing_diamond: "\ue0b4 "
        background: "p:gray_light"
        foreground: "p:gray"
        template: "{{ if .PackageManagerIcon }} {{ .PackageManagerIcon }} {{ end }}"
        properties:
          fetch_package_manager: true
        background_templates:
          - '{{ if eq .PackageManagerName "npm" }}p:red_light{{ end }}'
          - '{{ if eq .PackageManagerName "yarn" }}p:blue_light{{ end }}'
          - '{{ if eq .PackageManagerName "pnpm" }}p:orange_light{{ end }}'
          - '{{ if eq .PackageManagerName "bun" }}p:yellow_light{{ end }}'
        foreground_templates:
          - '{{ if eq .PackageManagerName "npm" }}p:red{{ end }}'
          - '{{ if eq .PackageManagerName "yarn" }}p:blue{{ end }}'
          - '{{ if eq .PackageManagerName "pnpm" }}p:orange{{ end }}'
          - '{{ if eq .PackageManagerName "bun" }}p:yellow{{ end }}'
