blocks:
  - type: rprompt
    alignment: right
    overflow: hide
    segments:
      # Perl runtime - diamond style when no project segment
      - type: perl
        style: diamond
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4 "
        background: "p:blue"
        foreground: "p:blue_lighter"
        template: "{{ if and (not .Segments.Project.Version) (.Full) }} \ue769 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} {{ end }}"

      # Perl runtime - powerline style when project segment exists
      - type: perl
        style: diamond
        trailing_diamond: "\ue0b4 "
        background: "p:blue"
        foreground: "p:blue_lighter"
        template: "{{ if and (.Segments.Project.Version) (.Full) }} \ue769 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} {{ end }}"
