# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 3
final_space: true
shell_integration: true
enable_cursor_positioning: true
tooltips_action: replace
