tooltips:
  # Terraform tooltip
  - type: terraform
    style: diamond
    leading_diamond: "\ue0b6"
    trailing_diamond: "\ue0b4"
    background: "p:purple"
    foreground: "p:purple_lighter"
    template: " \ue20f {{ .WorkspaceName }} "
    tips:
      - terraform
      - tf
