blocks:
  # Left prompt segments
  - type: prompt
    alignment: left
    segments:
      - type: text
        style: plain
        background: "p:transparent"
        template: "├─ "
        foreground_templates:
          - '{{ if eq .OS "darwin" }}p:purple{{ end }}'
          - '{{ if eq .OS "linux" }}p:yellow{{ end }}'
          - '{{ if eq .OS "windows" }}p:blue{{ end }}'

      # OS icon (first segment, only show when no error)
      - type: os
        style: diamond
        leading_diamond: "\ue0b6"
        background: "p:gray"
        foreground: "p:gray_light"
        template: "{{ if eq .Code 0 }}{{ .Icon }}  {{ end }}"
        background_templates:
          - '{{ if eq .OS "darwin" }}p:purple{{ end }}'
          - '{{ if eq .OS "linux" }}p:yellow{{ end }}'
          - '{{ if eq .OS "windows" }}p:blue{{ end }}'
        foreground_templates:
          - '{{ if eq .OS "darwin" }}p:purple_lighter{{ end }}'
          - '{{ if eq .OS "linux" }}p:yellow_darker{{ end }}'
          - '{{ if eq .OS "windows" }}p:blue_lighter{{ end }}'
