blocks:
  - type: prompt
    alignment: left
    segments:
      # Directory (from $directory)
      - type: path
        style: diamond
        trailing_diamond: "\ue0b4 "
        background: "p:teal"
        foreground: "p:teal_darker"
        properties:
          home_icon: "\ue617 "
          style: agnoster_short
          max_depth: 1
